<?php

namespace Netwerkstatt\SilverstripeRector\Tests\Set\Silverstripe54\Fixture;

use SilverStripe\Dev\DevelopmentAdmin;

class MyDevAdmin extends DevelopmentAdmin
{
}
?>
-----
<?php

namespace Netwerkstatt\SilverstripeRector\Tests\Set\Silverstripe54\Fixture;

use SilverStripe\Dev\DevelopmentAdmin;

/**
 * @deprecated DevelopmentAdmin has been deprecated. It will be removed without equivalent functionality to replace it.
 * See: https://docs.silverstripe.org/en/5/changelogs/5.4.0/#deprecated-api
 */
class MyDevAdmin extends DevelopmentAdmin
{
}
?>
