#!/bin/bash

## Description: run PHPStan
## Usage: stan
## Example: "ddev stan"

if ! [ -x "$(command -v vendor/bin/phpstan)" ]; then
  echo 'Error: phpstan/phpstan is not installed.' >&2
  echo 'Please add it as a composer requirement.' >&2
  exit 1
fi

php vendor/bin/phpstan
